/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_exp_test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "s21_math.h"

START_TEST(s21_exp_0)
{
double x = 0;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_1)
{
double x = 1;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_2)
{
double x = 2;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_3)
{
double x = 3;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_4)
{
double x = 1.5;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_5)
{
double x = -1.5;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_6)
{
double x = 0.5;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_7)
{
double x = -0.5;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_8)
{
double x = 715;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_9)
{
double x = -715;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_10)
{
double x = -0;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_11)
{
double x = 'A';
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_12)
{
double x = -'N';
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_13)
{
double x = - 'V';
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_14)
{
double x = + 'B';
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_15)
{
double x = 0 / 1;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST

START_TEST(s21_exp_16)
{
double x = 0 / 1;
ck_assert_int_eq(s21_exp(x), exp(x));

}
END_TEST


int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1);
    tcase_add_test(tc1, s21_exp_0);
    tcase_add_test(tc1, s21_exp_1);
    tcase_add_test(tc1, s21_exp_2);
    tcase_add_test(tc1, s21_exp_3);
    tcase_add_test(tc1, s21_exp_4);
    tcase_add_test(tc1, s21_exp_5);
    tcase_add_test(tc1, s21_exp_6);
    tcase_add_test(tc1, s21_exp_7);
    tcase_add_test(tc1, s21_exp_8);
    tcase_add_test(tc1, s21_exp_9);
    tcase_add_test(tc1, s21_exp_10);
    tcase_add_test(tc1, s21_exp_11);
    tcase_add_test(tc1, s21_exp_12);
    tcase_add_test(tc1, s21_exp_13);
    tcase_add_test(tc1, s21_exp_14);
    tcase_add_test(tc1, s21_exp_15);
    tcase_add_test(tc1, s21_exp_16);

    srunner_set_fork_status(sr, CK_NOFORK);
    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}

